README.md

Actualizado README.md principal

---

frontend/controllers/SiteController.php
frontend/models/SignupForm.php

Cuando un usuario se registra, se envía un correo de confirmación con una url que debe ser usada para poder activar la cuenta.
En entorno de desarrollo, no se enviarán mails reales, esto se configurará más adelante.
Close #38

Correo de confirmación

---

common/models/UsuariosCompleto.php
common/models/UsuariosCompletoSearch.php
frontend/controllers/UsuariosCompletoController.php
frontend/views/layouts/main.php
frontend/views/site/index.php
frontend/views/usuarios-completo/_form.php
frontend/views/usuarios-completo/_search.php
frontend/views/usuarios-completo/index.php
frontend/views/usuarios-completo/view.php

El botón "ver mi perfil" aparecerá en la barra de navegación cuando el usuario se encuentre loggeado, y éste lo llevará a visualizar su propio perfil.
Closes #44

Botón para ver mi perfil

---

db/artchive-datos.sql
db/artchive.sql

Los usuarios pueden iniciar y cerrar sesión.
Close #47 
Close #48

Iniciar y cerrar sesión

---

common/config/main.php
common/models/UsuariosCompleto.php
common/models/UsuariosDatos.php
db/artchive-datos.sql
frontend/controllers/UsuariosDatosController.php
frontend/views/site/index.php
frontend/views/usuarios-completo/index.php
frontend/views/usuarios-completo/view.php
frontend/views/usuarios-datos/_form.php
frontend/views/usuarios-datos/update.php

El usuario común puede modificar su propio perfil, nunca el de otros.
Close #41

Modificar propio perfil

---

frontend/controllers/UsuariosCompletoController.php
frontend/controllers/UsuariosDatosController.php
frontend/views/layouts/main.php
frontend/views/usuarios-completo/index.php

Se ha añadido de forma provisional el link "Usuarios" a la barra de navegación. A futuro se le buscará un lugar más adecuado.
Los usuarios conectados podrán acceder a la lista de usuarios, así como una vista detallada de sus perfiles al hacer click en sus username.
En el caso de intentar acceder sin estar conectado, se redirigirá automáticamente a la pantalla de login.
Close #43

Se pueden ver los usuarios

---

frontend/controllers/SiteController.php
frontend/views/site/requestPasswordResetToken.php
frontend/views/site/resetPassword.php

Al pinchar en el link de recuperar contraseña el usuario recibirá un correo que lo llevará a un formulario dónde le pedirá que introduzca la nueva contraseña.
En entorno de desarrollo no se envían correos, éstos son guardados en la carpeta runtime en frontend.
Close #46

Recuperar contraseña

---

common/models/Personajes.php
common/models/PersonajesSearch.php
common/models/UsuariosCompleto.php
frontend/controllers/PersonajesController.php
frontend/views/layouts/main.php
frontend/views/personajes/_form.php
frontend/views/personajes/_search.php
frontend/views/personajes/create.php
frontend/views/personajes/index.php
frontend/views/personajes/update.php
frontend/views/personajes/view.php
frontend/views/site/requestPasswordResetToken.php
frontend/views/usuarios-completo/view.php

Un usuario puede crear personajes.
Close #64 
- Se ha adelantad la visualización de personajes propios en el perfil #45 . **Pendiente de revisar.**
- Se ha adelantado la modificación de personajes #65 . **Pendiente de revisar.**
- Se ha adelantado la eliminación de personaje #66 . **Pendiente de revisar.**
- Se ha adelantado la visualización de todos los personajes #67 . **Pendiente de revisar.**

Crear personajes

---

common/models/Personajes.php
frontend/views/personajes/update.php
frontend/views/personajes/view.php

El usuario puede modificar sus propios personajes.
En ningún caso podrá modificar los personajes de otro usuario.
Close #65

Modificar personajes

---

common/models/Personajes.php
frontend/controllers/PersonajesController.php
frontend/views/personajes/view.php

Un usuario puede borrar sus propios personajes.
En ningún caso un usuario puede borrar personajes ajenos.
Close #66 
- Se ha refactorizado parte de "modificar personaje" #117

Eliminar personaje

---

common/config/main.php
common/models/Personajes.php
common/models/UsuariosCompleto.php
frontend/controllers/PersonajesController.php
frontend/controllers/UsuariosCompletoController.php
frontend/controllers/UsuariosDatosController.php
frontend/views/usuarios-completo/index.php
frontend/views/usuarios-completo/personajes.php
frontend/views/usuarios-completo/view.php

Un usuario puede ver sus personajes desde su perfil, también puede ver los de otros usuarios.
Close #67 
- Se han refactorizado algunos códigos.
- Se ha tomado la decisión de que el email sea privado (sólo el dueño de la cuenta puede ver su propio email).
- Se ha tomado la decisión de que el id del usuario nunca será visible, se usará el username como parámetro.

Ver personajes

---

common/models/Publicaciones.php
common/models/PublicacionesSearch.php
db/artchive.sql
frontend/controllers/PublicacionesController.php
frontend/views/layouts/main.php
frontend/views/personajes/create.php
frontend/views/publicaciones/_form.php
frontend/views/publicaciones/_search.php
frontend/views/publicaciones/create.php
frontend/views/publicaciones/index.php
frontend/views/publicaciones/update.php
frontend/views/publicaciones/view.php

Un usuario puede crear publicaciones.
Close #73

Crear publicaciones

---

common/config/main.php
common/models/MensajesPrivados.php
common/models/MensajesPrivadosSearch.php
common/models/User.php
db/artchive-datos.sql
db/artchive.sql
frontend/controllers/MensajesPrivadosController.php
frontend/views/layouts/main.php
frontend/views/mensajes-privados/_form.php
frontend/views/mensajes-privados/_search.php
frontend/views/mensajes-privados/create.php
frontend/views/mensajes-privados/index.php
frontend/views/mensajes-privados/sent.php
frontend/views/mensajes-privados/update.php
frontend/views/mensajes-privados/view.php

El usuario puede ver su bandeja de entrada (recibidos y enviados). En ningún caso se podrán ver bandejas de entradas de otros usuarios, no está contemplado así que no se da lugar a ello.
El usuario sólo puede visualizar un mensaje si es o bien receptor o bien emisor de éste.
Closes #56

Ver bandeja de entrada

---

common/config/main.php
common/models/MensajesPrivados.php
common/models/MensajesPrivadosSearch.php
common/models/UsuariosCompleto.php
frontend/controllers/MensajesPrivadosController.php
frontend/views/layouts/main.php
frontend/views/mensajes-privados/_form.php
frontend/views/mensajes-privados/create.php
frontend/views/mensajes-privados/index.php
frontend/views/mensajes-privados/sent.php
frontend/views/personajes/view.php
frontend/views/usuarios-completo/personajes.php
frontend/views/usuarios-completo/view.php

El usuario puede enviar un mensaje privado, indicando el nombre de usuario al que desea enviarle.
- Se han añadido botones de "enviar mp" en los perfiles de los usuarios.
- Se han adecentado un poco más las url.
- Se ha cambiado el modo de visualización de los mensajes privados para que se vea el nombre del emisor y del receptor en vez del id.
Close #57

Enviar mensaje privado

---

common/config/main.php
common/models/Seguidores.php
common/models/SeguidoresSearch.php
common/models/User.php
common/models/UsuariosCompleto.php
db/artchive.sql
frontend/controllers/SeguidoresController.php
frontend/views/seguidores/_form.php
frontend/views/seguidores/_search.php
frontend/views/seguidores/create.php
frontend/views/seguidores/index.php
frontend/views/seguidores/update.php
frontend/views/seguidores/view.php
frontend/views/usuarios-completo/view.php

Los usuarios pueden ver sus seguidores 
Close #55

Ver seguidores

---

common/models/UsuariosCompleto.php
frontend/controllers/SeguidoresController.php
frontend/views/seguidores/following.php

Los usuarios pueden ver a quienes siguen otros usuarios.
Close #54

Ver seguidos

---

common/models/Notificaciones.php
common/models/NotificacionesSearch.php
db/artchive-datos.sql
db/artchive.sql
frontend/controllers/NotificacionesController.php
frontend/views/layouts/main.php
frontend/views/notificaciones/_form.php
frontend/views/notificaciones/_search.php
frontend/views/notificaciones/create.php
frontend/views/notificaciones/index.php
frontend/views/notificaciones/update.php
frontend/views/notificaciones/view.php

Un usuario puede ver sus propias notificaciones, éstas incluirán un link y se clasificarán por tipo (próximamente).
Close #61

Ver notificaciones

---

common/models/Personajes.php
common/models/User.php
frontend/assets/AppAsset.php
frontend/controllers/SiteController.php
frontend/views/layouts/main.php
frontend/views/personajes/index.php
frontend/views/site/index.php
frontend/views/site/search.php
frontend/views/usuarios-completo/index.php
frontend/views/usuarios-completo/view.php
frontend/web/css/custom.css

La aplicación permite buscar usuarios. También se ha implementado la búsqueda de personajes.
Los usuarios se buscan por username, y los personajes por nombre. 
Se ha añadido una barra de búsqueda a la navbar.
Close #68 
Close #69

Buscar usuario

---

frontend/views/layouts/main.php
frontend/views/site/index.php
frontend/web/css/custom.css

Se ha mejorado la navbar, imitando el estilo de twitter.

Navbar estilo twitter

---

common/models/Publicaciones.php
common/models/UsuariosCompleto.php
frontend/views/usuarios-completo/view.php

Se le suma al apartado de personajes recientes, así que toda la información del usuario ya está vinculada en su perfil.
Closes #45

Publicaciones recientes en perfil

---

common/models/Publicaciones.php
frontend/views/publicaciones/create.php
frontend/views/publicaciones/update.php
frontend/views/publicaciones/view.php

Un usuario común sólo puede editar o borrar las publicaciones que le pertenecen.
Close #74 
Close #75

Editar publicaciones

---

frontend/controllers/PersonajesController.php
frontend/controllers/PublicacionesController.php
frontend/views/publicaciones/index.php

Se ven las publicaciones en relación a su usuario.
Closes #76

Ver publicaciones

---

common/models/UsuariosCompleto.php
frontend/controllers/UsuariosCompletoController.php
frontend/views/usuarios-completo/view.php

Un usuario puede seguir y dejar de seguir a otro.
La funcionalidad se ha implementado dinámicamente con AJAX.
close #52 
close #53 
close #19 
close #17

Seguir y dejar de seguir

---

common/models/Bloqueos.php
common/models/UsuariosCompleto.php
db/artchive.sql
frontend/assets/AppAsset.php
frontend/controllers/BloqueosController.php
frontend/controllers/UsuariosCompletoController.php
frontend/views/publicaciones/_comentarios.php
frontend/views/usuarios-completo/view.php
frontend/web/js/profile.js

Se pueden bloquear a otros usuarios.
Al bloquear un usuario:
- Se dejará de seguir a éste si se estaba siguiendo.
- Si el usuario nos estaba siguiendo dejará de hacerlo.
Close #60

Bloquear a un usuario

---

common/models/User.php
frontend/assets/AppAsset.php
frontend/controllers/UsuariosCompletoController.php
frontend/views/layouts/main.php
frontend/views/notificaciones/index.php
frontend/web/js/extra.js

Se muestra el número de notificaciones pendientes, y se va actualizando según se van recibiendo.
Se considera que una notificacion ha sido "vista" cuando se entra en la pestaña de notificaciones.

Notificaciones

---

common/models/Relaciones.php
common/models/Solicitudes.php
db/artchive.sql
frontend/controllers/SolicitudesController.php
frontend/views/solicitudes/view.php

- Se pueden aceptar las solicitudes de relaciones. Close #81 
- Se pueden rechazar las solicitudes de relaciones. Close #82 
Al rechazar una solicitud: la relación creada que estaba en espera se elimina y relacion_id pasa a ser null.
Al aceptar la solicitud: la relación creada que estaba en espera queda validada y se muestra.

Aceptar y rechazar

---

common/messages/en-EN/frontend/long.php
frontend/assets/AppAsset.php
frontend/controllers/DeleteAccountController.php
frontend/views/delete-account/_form.php
frontend/views/delete-account/index.php
frontend/views/layouts/secondary.php
frontend/views/usuarios-datos/update.php
frontend/web/js/delete-account.js

Para la baja de una cuenta se abrirá una ventana emergente en la que habrá que introducir el nombre de usuario para validar la baja.
Una vez se valida la baja, la ventana secundaria se cierra y la primaria se actualiza para mostrar el mensaje de borrado.
Close #13

# Gestion de ventanas

---

backend/views/layouts/main.php
common/models/Comentarios.php
common/models/MensajesPrivados.php
common/models/UsuariosCompleto.php
frontend/controllers/MensajesPrivadosController.php
frontend/views/mensajes-privados/_view.php
frontend/views/mensajes-privados/index.php
frontend/views/mensajes-privados/sent.php
frontend/views/reportes/index.php
frontend/web/css/homelogged.css
frontend/web/css/site.css
frontend/web/js/comentarios.js

- Cambio la apariencia del view.
- Añado responder y borrar en view de mensajes privados.

Mensajes Privados

---

common/messages/en-EN/app.php
common/messages/en-EN/frontend.php
common/models/Solicitudes.php
frontend/views/solicitudes/view.php
frontend/web/css/homelogged.css

- Cambio la apariencia de las solicitudes.
- Cambio algunas traducciones.
- Arreglo algunos detalles.

Solicitudes
